### ISSUE TITLE
Web-ifc-viewer hello world tutorial

### ISSUE THREAD

**Issue by agviegas** [IFCjs/info#25]
## 📋 GENERAL: 

- Bounties page: https://bounties.ifcjs.io/
- Required skills: `IFC.js`.
- Bounty: $100.

________________________________________________________________________

## ⚔ CHALLENGE:

We need more tutorials to show to the world how to use IFC.js and what can they do with it. We already have some tutorials in the documentation, so this is just a matter of creating a new one. For example:

- https://ifcjs.github.io/info/docs/Hello%20world

The tutorial should be made in the repository IFCjs/info. We use docusaurus for documentation. No worries, you don't need to know docusaurus to do this: just copy and paste what we do in other tutorials and you should be ready to go.

- https://github.com/ifcjs/info

The example developed in the tutorial should be made in the repository IFCjs/hello-world.

- https://github.com/ifcjs/hello-world

________________________________________________________________________

## 👩‍⚖️ REQUIREMENTS: 

- Similar look to other tutorials.

________________________________________________________________________

## 🔥 STARTING MATERIAL: 

Take a look at how other tutorials are made, and ask us anything you need!

**Comment by AnweshGangula** [comment]
Hi, I will work on this tutorial and get it done by Tuesday May 24, 2022

**Comment by agviegas** [comment]
Fantastic @AnweshGangula! It's yours.

**Comment by AnweshGangula** [comment]
@agviegas, I've added the documentation and created a PR here #52

**Comment by agviegas** [comment]
Awesome! We'll review it these days and let you know 😁 it looks good!

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by agviegas** [comment]
Hey @AnweshGangula did you submit the expense for OpenCollective for this? You'll need to do it in order to get the money for this bounty 🙂 Cheers!
