### ISSUE TITLE
web-ifc-viewer API page

### ISSUE THREAD

**Issue by agviegas** [IFCjs/info#27]
## 📋 GENERAL: 

- Bounties page: https://bounties.ifcjs.io/
- Required skills: `IFC.js`.
- Bounty: $100.

________________________________________________________________________

## ⚔ CHALLENGE:

Document web-ifc-viewer API, like we did with web-ifc-three: 

- https://ifcjs.github.io/info/docs/Guide/web-ifc-three/api

________________________________________________________________________

## 👩‍⚖️ REQUIREMENTS: 

- Similar look to web-ifc-three API page.

________________________________________________________________________

## 🔥 STARTING MATERIAL: 

Ask us anything you need!

**Comment by Jsanchez4** [comment]
Hi Antonio, I'll take care of this one! It will be ready for 30.05 max
