### ISSUE TITLE
web-ifc API

### ISSUE THREAD

**Issue by agviegas** [IFCjs/info#28]
## 📋 GENERAL: 

- Bounties page: https://bounties.ifcjs.io/
- Required skills: `IFC.js`.
- Bounty: $100.

________________________________________________________________________

## ⚔ CHALLENGE:

Document web-ifc API, like we did with web-ifc-three: 

- https://ifcjs.github.io/info/docs/Guide/web-ifc-three/api

________________________________________________________________________

## 👩‍⚖️ REQUIREMENTS: 

- Similar look to web-ifc-three API page.

________________________________________________________________________

## 🔥 STARTING MATERIAL: 

Ask us anything you need!

**Comment by Jsanchez4** [comment]
I would like to take on this task. I can have it by 06/24
