### ISSUE TITLE
web-ifc-viewer JSON property tutorial

### ISSUE THREAD

**Issue by agviegas** [IFCjs/info#32]
## 📋 GENERAL: 

- Bounties page: https://bounties.ifcjs.io/
- Required skills: `IFC.js`.
- Bounty: $100.

________________________________________________________________________

## ⚔ CHALLENGE:

We need more tutorials to show to the world how to use IFC.js and what can they do with it. We already have some tutorials in the documentation, so this is just a matter of creating a new one. For example:

- https://ifcjs.github.io/info/docs/Hello%20world

The tutorial should be made in the repository IFCjs/info. We use docusaurus for documentation. No worries, you don't need to know docusaurus to do this: just copy and paste what we do in other tutorials and you should be ready to go.

- https://github.com/ifcjs/info

The example developed in the tutorial should be made in the repository IFCjs/hello-world.

- https://github.com/ifcjs/hello-world

________________________________________________________________________

## 👩‍⚖️ REQUIREMENTS: 

- Similar look to other tutorials.

________________________________________________________________________

## 🔥 STARTING MATERIAL: 

Take a look at how other tutorials are made, and ask us anything you need!

**Comment by seantai** [comment]
working on this

**Comment by arunkvijay** [comment]
Hi @agviegas , I would like to go for this.

**Comment by pkpndy** [comment]
> Hi @agviegas , I would like to go for this.

Hi @arunkvijay , Comment "::take" and you will be auto assigned by bot.

**Comment by pkpndy** [comment]
> Hi @agviegas , I would like to go for this.

Hi @arunkvijay , Comment `:take` and you will be auto assigned by bot.

**Comment by arunkvijay** [comment]
:take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @arunkvijay! Thanks for taking this bounty! The due date is August 26, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @ to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment]
Hi, @arunkvijay! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the ::expense::_____ command (replace the _____ with the invoice number).

**Comment by agviegas** [comment]
::done

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::done

Hi, @arunkvijay! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).

**Comment by arunkvijay** [comment]
::expense::92720

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::expense::92720

Hi, @arunkvijay! Thanks for the confirmation! We’ll proceed to review the expense. Once it’s approved, the payment will be scheduled.

**Comment by agviegas** [comment]
### 🟢🟢🟢

Hi, @arunkvijay! Your [expense](https://opencollective.com/ifcjs/expenses/92720) has been approved!

**Comment by agviegas** [comment]
### 🟢🟢🟢

Hi, @arunkvijay! Your [expense](https://opencollective.com/ifcjs/expenses/92720) has been approved!

**Comment by agviegas** [comment]
### 🟢🟢🟢

Hi, @arunkvijay! Your [expense](https://opencollective.com/ifcjs/expenses/92720) has been approved!

**Comment by agviegas** [comment]
### 🎉🎉🎉

Hi, @arunkvijay! Thanks for your contributions! The reward of this bounty has been transferred to your Open Collective account.
