### ISSUE TITLE
web-ifc-viewer + mapbox tutorial

### ISSUE THREAD

**Issue by agviegas** [IFCjs/info#33]
## 📋 GENERAL: 

- Bounties page: https://bounties.ifcjs.io/
- Required skills: `IFC.js`.
- Bounty: $100.

________________________________________________________________________

## ⚔ CHALLENGE:

We need more tutorials to show to the world how to use IFC.js and what can they do with it. We already have some tutorials in the documentation, so this is just a matter of creating a new one. For example:

- https://ifcjs.github.io/info/docs/Hello%20world

The tutorial should be made in the repository IFCjs/info. We use docusaurus for documentation. No worries, you don't need to know docusaurus to do this: just copy and paste what we do in other tutorials and you should be ready to go.

- https://github.com/ifcjs/info

The example developed in the tutorial should be made in the repository IFCjs/hello-world.

- https://github.com/ifcjs/hello-world

________________________________________________________________________

## 👩‍⚖️ REQUIREMENTS: 

- Similar look to other tutorials.

________________________________________________________________________

## 🔥 STARTING MATERIAL: 

Take a look at how other tutorials are made, and ask us anything you need!

**Comment by Shalwaban** [comment]
working on this til Sun June 5th

**Comment by seantai** [comment]
added this, it looks like it got merged with this other pull request https://github.com/IFCjs/info/pull/58

**Comment by agviegas** [comment]
@seantai  No problem, I the mapbox tutorial looks super good! The picking example has some suggestions. When you implement them, I'll merge everything and you'll get both bounties. 🙂 Contact us if you have any questions. Cheers!
