### ISSUE TITLE
B#13 web-ifc-viewer Memory Disposal Tutorial

### ISSUE THREAD

**Issue by agviegas** [IFCjs/info#34]
## 📋 GENERAL: 

- Bounties page: https://bounties.ifcjs.io/
- Required skills: `IFC.js`.
- Bounty: $100.

________________________________________________________________________

## ⚔ CHALLENGE:

We need more tutorials to show to the world how to use IFC.js and what can they do with it. We already have some tutorials in the documentation, so this is just a matter of creating a new one. For example:

- https://ifcjs.github.io/info/docs/Hello%20world

The tutorial should be made in the repository IFCjs/info. We use docusaurus for documentation. No worries, you don't need to know docusaurus to do this: just copy and paste what we do in other tutorials and you should be ready to go.

- https://github.com/ifcjs/info

The example developed in the tutorial should be made in the repository IFCjs/hello-world.

- https://github.com/ifcjs/hello-world

________________________________________________________________________

## 👩‍⚖️ REQUIREMENTS: 

- Similar look to other tutorials.

________________________________________________________________________

## 🔥 STARTING MATERIAL: 

Take a look at how other tutorials are made, and ask us anything you need!

**Comment by seantai** [comment]
working on this

**Comment by agviegas** [comment]
All yours @seantai !

**Comment by agviegas** [comment]
Hey @seantai how are you going on this one? No rush whatsoever, just to confirm that you are still on this 🙂 Cheers

**Comment by seantai** [comment]
Will finish this one now that the other 2 just got confirmed. Wanted to make sure I was following a correct format.

**Comment by agviegas** [comment]
### 🟢🟢🟢

Hi, @seantai ! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).

**Comment by seantai** [comment]
::expense::#90018
