### ISSUE TITLE
web-ifc-viewer picking / selection tutorial

### ISSUE THREAD

**Issue by agviegas** [IFCjs/info#35]
## 📋 GENERAL: 

- Bounties page: https://bounties.ifcjs.io/
- Required skills: `IFC.js`.
- Bounty: $100.

________________________________________________________________________

## ⚔ CHALLENGE:

We need more tutorials to show to the world how to use IFC.js and what can they do with it. We already have some tutorials in the documentation, so this is just a matter of creating a new one. For example:

- https://ifcjs.github.io/info/docs/Hello%20world

The tutorial should be made in the repository IFCjs/info. We use docusaurus for documentation. No worries, you don't need to know docusaurus to do this: just copy and paste what we do in other tutorials and you should be ready to go.

- https://github.com/ifcjs/info

The example developed in the tutorial should be made in the repository IFCjs/hello-world.

- https://github.com/ifcjs/hello-world

________________________________________________________________________

## 👩‍⚖️ REQUIREMENTS: 

- Similar look to other tutorials.

________________________________________________________________________

## 🔥 STARTING MATERIAL: 

Take a look at how other tutorials are made, and ask us anything you need!

**Comment by Shalwaban** [comment]
working on this !

**Comment by Shalwaban** [comment]
submitted pull request for the Doc portion under my real github account. 
any feedback appreciated.

**Comment by seantai** [comment]
also submitted example in hello-world

**Comment by agviegas** [comment]
@seantai I added some comments to the PR!
