### ISSUE TITLE
B#18: web-ifc hello world Tutorial

### ISSUE THREAD

**Issue by agviegas** [IFCjs/info#36]
## 📋 GENERAL: 

- Bounties page: https://bounties.ifcjs.io/
- Required skills: `IFC.js`.
- Bounty: $100.

________________________________________________________________________

## ⚔ CHALLENGE:

We need more tutorials to show to the world how to use IFC.js and what can they do with it. We already have some tutorials in the documentation, so this is just a matter of creating a new one. For example:

- https://ifcjs.github.io/info/docs/Hello%20world

The tutorial should be made in the repository IFCjs/info. We use docusaurus for documentation. No worries, you don't need to know docusaurus to do this: just copy and paste what we do in other tutorials and you should be ready to go.

- https://github.com/ifcjs/info

The example developed in the tutorial should be made in the repository IFCjs/hello-world.

- https://github.com/ifcjs/hello-world

________________________________________________________________________

## 👩‍⚖️ REQUIREMENTS: 

- Similar look to other tutorials.

________________________________________________________________________

## 🔥 STARTING MATERIAL: 

Take a look at how other tutorials are made, and ask us anything you need!

**Comment by DrSensor** [comment]
Hi, can I grab this issue?

Also, does the tutorial need to target nodejs too? Or just browser? 🤔
Asking since I just notice there is `node` folder in the examples/web-ifc/ifc-to-json/

**Comment by DrSensor** [comment]
Nevermind, I've made a draft for this tutorial and explaining how it can be used in the backend or script for automation seems interesting.

I can finish the tutorial before Sunday, 5 June 2022

**Comment by agviegas** [comment]
Hey @DrSensor right now IFC.js is more focused towards frontend, so it would be great if this tutorial covered at least a frontend hello world. If you also did the backend, we can add that as part of this same tutorial, so it would cover the very basics of both things. 🙂

**Comment by agviegas** [comment]
Hey @DrSensor how is this going? Any estimated date for this? No rush, just to confirm that you are still on this. Cheers!

**Comment by agviegas** [comment]
I'm opening this again!

**Comment by TxTony** [comment]
Hi,
you mean the hello  world tuto should cover something like this :
- display a list of spaces
- select a space display its informations
- display result on screen with "wondeful html + css "  :) 
- 
![image](https://user-images.githubusercontent.com/9210019/185460711-f55a56a6-6f45-4891-a589-9287cd00b3b7.png)

PS : i've displayed the information in my console to make this fast

**Comment by TxTony** [comment]
Can I take the issue i'll make a PR today or this week. if i can't release it the next week for any reason  i'll tell you.

to summup i just have to show how to 
- setting up the project
- load a model with web-ifc ( by input file or http request doesn't matter ) 
- show the ifcApi can grab a line to conclude
- display the result in a html page ( don't need to style it ) 

Other basic and advanced tutorial will come later right ?

**Comment by agviegas** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @agviegas! Thanks for taking this bounty! The due date is September 11, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment]
::drop

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::drop

Hi, @agviegas! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by agviegas** [comment]
@TxTony sure! Just use the ::take command like I did and it's yours. You need to set up the full example [in the examples repo](https://github.com/IFCjs/hello-world) and the tutorial with the step-by-step in this repo. If you see other tutorials, you'll see that we create a component that references the URL of the example repo app. 

Indeed, bounties more advanced tutorials will be released soon 🙂 Let us know if you have any questions!

**Comment by TxTony** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @TxTony! Thanks for taking this bounty! The due date is September 12, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment]
🟢🟢🟢

Hi, @TxTony! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).

**Comment by TxTony** [comment]
::expense::92190

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::expense::92190

Hi, @TxTony! Thanks for the confirmation! We’ll proceed to review the expense. Once it’s approved, the payment will be scheduled.

**Comment by agviegas** [comment]
### 🟢🟢🟢

Hi, @TxTony! Your [expense](https://opencollective.com/ifcjs/expenses/92190) has been approved!

**Comment by agviegas** [comment]
### 🎉🎉🎉

Hi, @TxTony! Thanks for your contributions! The reward of this bounty has been transferred to your Open Collective account.
