### ISSUE TITLE
web-ifc property reading tutorial

### ISSUE THREAD

**Issue by agviegas** [IFCjs/info#37]
## 📋 GENERAL: 

- Bounties page: https://bounties.ifcjs.io/
- Required skills: `IFC.js`.
- Bounty: $100.

________________________________________________________________________

## ⚔ CHALLENGE:

We need more tutorials to show to the world how to use IFC.js and what can they do with it. We already have some tutorials in the documentation, so this is just a matter of creating a new one. For example:

- https://ifcjs.github.io/info/docs/Hello%20world

The tutorial should be made in the repository IFCjs/info. We use docusaurus for documentation. No worries, you don't need to know docusaurus to do this: just copy and paste what we do in other tutorials and you should be ready to go.

- https://github.com/ifcjs/info

The example developed in the tutorial should be made in the repository IFCjs/hello-world.

- https://github.com/ifcjs/hello-world

________________________________________________________________________

## 👩‍⚖️ REQUIREMENTS: 

- Similar look to other tutorials.

________________________________________________________________________

## 🔥 STARTING MATERIAL: 

Take a look at how other tutorials are made, and ask us anything you need!

**Comment by aka-blackboots** [comment]
Let me know @agviegas if this is what you're looking for, I tried recreating it like what forge does. If this is what is needed I can contribute to this and will create more nice UI and UX for it. 

1. Item Properties
2. Element Properties
3. Material Properties
4. Psets

![Screenshot (383)](https://user-images.githubusercontent.com/47943405/169295384-a53addbd-c8cd-4fee-a13b-4153526c103c.png)

**Comment by agviegas** [comment]
Hi @aka-blackboots! That looks great, but what we need is something focused on web-ifc. Something like [this](https://github.com/tomvandig/web-ifc/blob/main/examples/usage/src/properties.ts). So no 3d, just IFC analysis. If you are up for it, I'll assign the tutorial to you!
