### ISSUE TITLE
B#20: web-ifc Property Editing Tutorial

### ISSUE THREAD

**Issue by agviegas** [IFCjs/info#38]
## 📋 GENERAL: 

- Bounties page: https://bounties.ifcjs.io/
- Required skills: `IFC.js`.
- Bounty: $100.

________________________________________________________________________

## ⚔ CHALLENGE:

We need more tutorials to show to the world how to use IFC.js and what can they do with it. We already have some tutorials in the documentation, so this is just a matter of creating a new one. For example:

- https://ifcjs.github.io/info/docs/Hello%20world

The tutorial should be made in the repository IFCjs/info. We use docusaurus for documentation. No worries, you don't need to know docusaurus to do this: just copy and paste what we do in other tutorials and you should be ready to go.

- https://github.com/ifcjs/info

The example developed in the tutorial should be made in the repository IFCjs/hello-world.

- https://github.com/ifcjs/hello-world

________________________________________________________________________

## 👩‍⚖️ REQUIREMENTS: 

- Similar look to other tutorials.

________________________________________________________________________

## 🔥 STARTING MATERIAL: 

Take a look at how other tutorials are made, and ask us anything you need!

**Comment by DrSensor** [comment]
I can also work on this tutorial in the next week. I estimate it will be done in a week or less.

**Comment by agviegas** [comment]
All yours @DrSensor !

**Comment by agviegas** [comment]
Hey @DrSensor how are you going with this? No rush, just to confirm you are still on this 🙂 Cheers!

**Comment by agviegas** [comment]
I'm opening this again!

**Comment by agviegas** [comment]
Hi @HassanEmam sure! We have just automated the bounty system :) Create a comment just containing the text `::take` and you will be good to go. You can see an example of that [here](https://github.com/ifcjs/info/issues/47#issuecomment-1205890048). Let me know if you have any other questions!

**Comment by HassanEmam** [comment]
::take

**Comment by HassanEmam** [comment]
I have made a PR for the documentation here and the code in the hello-world repo

**Comment by agviegas** [comment]
@HassanEmam try using take again! I'll review the PR right away :)

**Comment by HassanEmam** [comment]
::take

**Comment by agviegas** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @agviegas! Thanks for taking this bounty! The due date is August 28, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment]
::drop

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::drop

Hi, @agviegas! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by agviegas** [comment]
@HassanEmam now it works 😅 sorry, we just set this up. Try one last time! Thanks in advance.

**Comment by HassanEmam** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @HassanEmam! Thanks for taking this bounty! The due date is August 28, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by HassanEmam** [comment]
Great it seems working now

**Comment by HassanEmam** [comment]
@agviegas I have created PR on both repos for documentation and examples and did not get any feedback

**Comment by agviegas** [comment]
🟢🟢🟢

Hi, @HassanEmam! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).

**Comment by HassanEmam** [comment]
::expense::91978

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::expense::91978

Hi, @HassanEmam! Thanks for the confirmation! We’ll proceed to review the expense. Once it’s approved, the payment will be scheduled.

**Comment by agviegas** [comment]
### 🟢🟢🟢

Hi, @HassanEmam! Your [expense](https://opencollective.com/ifcjs/expenses/91978) has been approved!

**Comment by agviegas** [comment]
### 🎉🎉🎉

Hi, @HassanEmam! Thanks for your contributions! The reward of this bounty has been transferred to your Open Collective account.
