### ISSUE TITLE
Maintainer programme

### ISSUE THREAD

**Issue by adamaymo** [IFCjs/info#40]
I am looking to contribute on the maintainer programme, specifically those tasks related to the design of new sections for the website (course, general page, etc.). I was not able to find the issues related to these bounties on any repository. Could you point me to where to find them?

Many thanks!

**Comment by VladT7** [comment]
Commenting as I would like to know as well! 

Kind regards, 
Vlad

**Comment by schubert-da** [comment]
Same really, couldn't find any issues linked with them on the bounty board so wanted to ask here as well.

Thanks!
