### ISSUE TITLE
IFC.js jobs page

### ISSUE THREAD

**Issue by agviegas** [IFCjs/info#41]
## 📋 GENERAL: 

- Required skills: `Nothing!`.
- Bounty: $100.

________________________________________________________________________

## ⚔ CHALLENGE:

We are going to publish a page to publish the job offers of companies and individuals looking for IFC.js devs to hire and collaborate. It will look similar to the crash course page:

- https://courses.ifcjs.io/crash-course

If you have never done a webpage before, don't worry because this is super easy and you don't need to code for this. This page is made in the mailerlite web editor, which is a drag and drop web page builder that you can learn in 10 minutes and for which you don't need to know how to program.

________________________________________________________________________

## 👩‍⚖️ REQUIREMENTS: 

- Similar look to the original crash course page.

- Using different clip art images. 

________________________________________________________________________

## 🔥 STARTING MATERIAL: 

- Internal video tutorial where we explain the whole process step by step.

- Internal document with the specifications of the page.

- Access to our account and the mailerlite online editor to create the page.

- Our graphics archive, from which you can extract the clip art images you want.

You can use Photopea, a free image editor that we use to edit the graphics a bit. 

- https://www.photopea.com/

**Comment by VladT7** [comment]
I'm interested in taking a crack at this! Looking to be done by 22:00 MST May 21.

**Comment by mirabotseva** [comment]
Hi, I would like to take this bounty. Would get it done by 23:00 CEST, May 22.

**Comment by agviegas** [comment]
Hi @mirabotseva ! Thanks for applying for this bounty. Unfortunately, this bounty is already taken by @bluecondor. No worries, because we'll keep publishing bounties like this. If you want to get updated before anyone else, you can subscribe to the bounty mailist: https://bounties.ifcjs.io/ .

**Comment by agviegas** [comment]
Hey @VladT7 do you have Discord? We are assembling a group with the other people that are helping with the pages to give you some indications 🙂

**Comment by VladT7** [comment]
Hi Antonio, I'm already on the IFC.js server! My username is ShrigmaMale
but I changed my nickname to Vlad. Looking forward to meeting the rest of
the team!

**Comment by VladT7** [comment]
Finished the page - you can find it on mailerlite under Websites > Jobs | IFC.js . I've left the "testimonials carousel" in as I think this could be a good place to showcase people who found jobs through our community - but it can be removed entirely. 

Also, I didn't touch any of the SEO page settings (not sure if we were supposed to) - so the page summary will still point to the IFC.js course description. Lastly, I took the liberty to edit the wording in some places, as it was a little bit awkward. 

If you have any questions or additional work needed to complete this bounty, don't hesitate to reach out!

**Comment by agviegas** [comment]
Fantastic job!
