### ISSUE TITLE
IFC.js Patreons Page

### ISSUE THREAD

**Issue by agviegas** [IFCjs/info#42]
## 📋 GENERAL: 

- Required skills: `Nothing!`.
- Bounty: $100.

________________________________________________________________________

## ⚔ CHALLENGE:

We want to create a page to tell the world how the patreon system works. We need a page similar to the crash course.

- https://courses.ifcjs.io/crash-course

If you have never done a webpage before, don't worry because this is super easy and you don't need to code for this. This page is made in the mailerlite web editor, which is a drag and drop web page builder that you can learn in 10 minutes and for which you don't need to know how to program.

________________________________________________________________________

## 👩‍⚖️ REQUIREMENTS: 

- Similar look to the original crash course page.

- Using different clip art images. 

________________________________________________________________________

## 🔥 STARTING MATERIAL: 

- Internal video tutorial where we explain the whole process step by step.

- Internal document with the specifications of the page.

- Access to our account and the mailerlite online editor to create the page.

- Our graphics archive, from which you can extract the clip art images you want.

You can use Photopea, a free image editor that we use to edit the graphics a bit. 

- https://www.photopea.com/

**Comment by bluecondor** [comment]
Hi! I could help out with this! I could do it by end of May.

P.S. I think the description of the task is copied and pasted from another task, but we can sort this out on discord :)

**Comment by Tubiotitooluwa** [comment]
Hi Antonio, I would love to get on this one. I have experience putting together presentation decks and a no code Web editor should be fun.
I can start by weekend if that is ok.
Cheers!.

**Comment by mirabotseva** [comment]
Hi, I would like to take this bounty. Would get it done by 23:00 CEST, May 25.

**Comment by agviegas** [comment]
Hi @mirabotseva and @Tubiotitooluwa! Thanks for applying for this bounty. Unfortunately, this bounty is already taken by @bluecondor. No worries, because we'll keep publishing bounties like this. If you want to get updated before anyone else, you can subscribe to the bounty mailist: https://bounties.ifcjs.io/ .

**Comment by Tubiotitooluwa** [comment]
Thank you for the update Antonio.
Looking forward to the next bounty!

**Comment by agviegas** [comment]
@Tubiotitooluwa this issue is available again, in case you'd like to take it (you were the second one to comment).

**Comment by Tubiotitooluwa** [comment]
Hi Antonio,
Absolutely! Rank you for the offer.

**Comment by agviegas** [comment]
@Tubiotitooluwa great! Are you in the discord server? If you speak to me (ansoni#0001) I'll bring you to the group where we're gathering all the page designers.

**Comment by Tubiotitooluwa** [comment]
@agviegas I just did

**Comment by Tubiotitooluwa** [comment]
I am not on the discord server, care to share?
