### ISSUE TITLE
IFC.js general page

### ISSUE THREAD

**Issue by agviegas** [IFCjs/info#43]
## 📋 GENERAL: 

- Required skills: `Nothing!`.
- Bounty: $100.

________________________________________________________________________

## ⚔ CHALLENGE:

We are going to publish an advanced BIM development course specialising in TypeScript, frontend, and React. We need a page similar to the crash course.

- https://courses.ifcjs.io/crash-course

If you have never done a webpage before, don't worry because this is super easy and you don't need to code for this. This page is made in the mailerlite web editor, which is a drag and drop web page builder that you can learn in 10 minutes and for which you don't need to know how to program.

________________________________________________________________________

## 👩‍⚖️ REQUIREMENTS: 

- Similar look to the original crash course page.

- Using different clip art images. 

________________________________________________________________________

## 🔥 STARTING MATERIAL: 

- Internal video tutorial where we explain the whole process step by step.

- Internal document with the specifications of the page.

- Access to our account and the mailerlite online editor to create the page.

- Our graphics archive, from which you can extract the clip art images you want.

You can use Photopea, a free image editor that we use to edit the graphics a bit. 

- https://www.photopea.com/

**Comment by schubert-da** [comment]
I would like to take this up @agviegas .
Should be able to deliver it in a week from getting the starting material.

**Comment by mirabotseva** [comment]
Hi, I would like to take this bounty. Would get it done by 23:00 CEST, May 25.

**Comment by agviegas** [comment]
Hi @mirabotseva! Thanks for applying for this bounty. Unfortunately, this bounty is already taken by @schubert-da. No worries, because we'll keep publishing bounties like this. If you want to get updated before anyone else, you can subscribe to the bounty mailist: https://bounties.ifcjs.io/ .
