### ISSUE TITLE
BIM Frontend Stack Course Page

### ISSUE THREAD

**Issue by agviegas** [IFCjs/info#44]
## 📋 GENERAL: 

- Required skills: `Nothing!`.
- Bounty: $100.

________________________________________________________________________

## ⚔ CHALLENGE:

We are going to publish an advanced BIM development course specialising in TypeScript, frontend, and React. We need a page similar to the crash course to announce it.

- https://courses.ifcjs.io/crash-course

If you have never done a webpage before, don't worry because this is super easy and you don't need to code for this. This page is made in the mailerlite web editor, which is a drag and drop web page builder that you can learn in 10 minutes and for which you don't need to know how to program.

________________________________________________________________________

## 👩‍⚖️ REQUIREMENTS: 

- Similar look to the original crash course page.

- Using different clip art images. 

________________________________________________________________________

## 🔥 STARTING MATERIAL: 

- Internal video tutorial where we explain the whole process step by step.

- Internal document with the specifications of the page.

- Access to our account and the mailerlite online editor to create the page.

- Our graphics archive, from which you can extract the clip art images you want.

You can use Photopea, a free image editor that we use to edit the graphics a bit. 

- https://www.photopea.com/

**Comment by rfdiazpr** [comment]
I am interested in this bounty.

**Comment by agviegas** [comment]
It's all yours ~ @rfdiazpr do you have Discord? So we can tell you more details. 😊

**Comment by rfdiazpr** [comment]
Yes - rfdiaz
