### ISSUE TITLE
B#21: Contribute to web-ifc Guide

### ISSUE THREAD

**Issue by agviegas** [IFCjs/info#45]
## 📋 GENERAL: 

- Bounties page: https://bounties.ifcjs.io/
- Required skills: `IFC.js`.
- Bounty: $100.

________________________________________________________________________

## ⚔ CHALLENGE:

We a guide for the people that want to contribute to the project. We already have step-by-step tutorials published:

- https://ifcjs.github.io/info/docs/Hello%20world

But this one wouldn't be a tutorial about how to use the library, but a tutorial about how to contribute to the library.

The tutorial should be made in the repository IFCjs/info. We use docusaurus for documentation. No worries, you don't need to know docusaurus to do this: just copy and paste what we do in other tutorials and you should be ready to go.

- https://github.com/ifcjs/info

The example developed in the tutorial should be made in the repository IFCjs/hello-world.

- https://github.com/ifcjs/hello-world

________________________________________________________________________

## 👩‍⚖️ REQUIREMENTS: 

- Similar look to other tutorials.

________________________________________________________________________

## 🔥 STARTING MATERIAL: 

- A 2 hours internal video explaining how to contribute to web-ifc.

Take a look at how other tutorials are made, and ask us anything you need!

**Comment by pkpndy** [comment]
@agviegas I can do this. Can you please assign this to me?

**Comment by agviegas** [comment]
Hi @pkpndy, sure. When do you plan to have this done?

**Comment by pkpndy** [comment]
> Hi @pkpndy, sure. When do you plan to have this done?

Thanks @agviegas , well I am thinking of doing this by the end of upcoming week.

Can I get few more details about the contribution? Like what kind of things are to be included.
Setting up the repo, practices to be followed, libraries to be installed, code of conduct, discord and communication channels, how to create a new issue.

**Comment by agviegas** [comment]
Hey @pkpndy, sure! You should include:
- How to clone the repository locally
- How to build it locally (either with emscripten or with docker)
- How to write code on it (preferably using an IDE that has a C++ compiler, or use docker)
- How to create a branch and submit the PR

**Comment by agviegas** [comment]
Hey @pkpndy we have just automated the bounty system :) Create a comment just containing the text ::take and you will be good to go. You can see an example of that [here](https://github.com/ifcjs/info/issues/47#issuecomment-1205890048). Let me know if you have any questions!

**Comment by pkpndy** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @pkpndy! Thanks for taking this bounty! The due date is August 26, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by pkpndy** [comment]
> Hey @pkpndy we have just automated the bounty system :) Create a comment just containing the text ::take and you will be good to go. You can see an example of that [here](https://github.com/ifcjs/info/issues/47#issuecomment-1205890048). Let me know if you have any questions!

Thanks @agviegas , I also checked the example you mentioned.

**Comment by pkpndy** [comment]
> Hey @pkpndy we have just automated the bounty system :) Create a comment just containing the text ::take and you will be good to go. You can see an example of that [here](https://github.com/ifcjs/info/issues/47#issuecomment-1205890048). Let me know if you have any questions!

Thanks @agviegas , I checked the example you mentioned. Do you want me to mention about this `::take` , `::drop` and `::done` automated system in the contribution guide?

**Comment by agviegas** [comment]
🟢🟢🟢

Hi, @pkpndy! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).

**Comment by pkpndy** [comment]
::expense::92063

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::expense::92063

Hi, @pkpndy! Thanks for the confirmation! We’ll proceed to review the expense. Once it’s approved, the payment will be scheduled.

**Comment by agviegas** [comment]
### 🟢🟢🟢

Hi, @pkpndy! Your [expense](https://opencollective.com/ifcjs/expenses/92063) has been approved!

**Comment by agviegas** [comment]
### 🟢🟢🟢

Hi, @pkpndy! Your [expense](https://opencollective.com/ifcjs/expenses/92063) has been approved!

**Comment by agviegas** [comment]
### 🟢🟢🟢

Hi, @pkpndy! Your [expense](https://opencollective.com/ifcjs/expenses/92063) has been approved!

**Comment by agviegas** [comment]
### 🟢🟢🟢

Hi, @pkpndy! Your [expense](https://opencollective.com/ifcjs/expenses/92063) has been approved!

**Comment by agviegas** [comment]
### 🎉🎉🎉

Hi, @pkpndy! Thanks for your contributions! The reward of this bounty has been transferred to your Open Collective account.
