### ISSUE TITLE
B#22: Contribute to web-ifc-three Guide

### ISSUE THREAD

**Issue by agviegas** [IFCjs/info#46]
## 📋 GENERAL: 

- Bounties page: https://bounties.ifcjs.io/
- Required skills: `IFC.js`.
- Bounty: $100.

________________________________________________________________________

## ⚔ CHALLENGE:

We a guide for the people that want to contribute to the project. We already have step-by-step tutorials published:

- https://ifcjs.github.io/info/docs/Hello%20world

But this one wouldn't be a tutorial about how to use the library, but a tutorial about how to contribute to the library.

The tutorial should be made in the repository IFCjs/info. We use docusaurus for documentation. No worries, you don't need to know docusaurus to do this: just copy and paste what we do in other tutorials and you should be ready to go.

- https://github.com/ifcjs/info

The example developed in the tutorial should be made in the repository IFCjs/hello-world.

- https://github.com/ifcjs/hello-world

________________________________________________________________________

## 👩‍⚖️ REQUIREMENTS: 

- Similar look to other tutorials.

________________________________________________________________________

## 🔥 STARTING MATERIAL: 

Take a look at how other tutorials are made, and ask us anything you need!

**Comment by pratik2315** [comment]
Hey! I am interested to work on this

**Comment by pkpndy** [comment]
@agviegas Can I take this?

**Comment by agviegas** [comment]
Hi @pratik2315 you commented first, so you have priority. When do you estimate to have this done? Cheers!

**Comment by pratik2315** [comment]
> Hi @pratik2315 you commented first, so you have priority. When do you estimate to have this done? Cheers!

Hey thanks! I don't know how I missed this notification. I suppose this is a docs issue related to making a detailed contribution guide for web-ifc-three right? Can I sort of get a second explanation of what specifically I will be working upon (github contribution guide or gitlab etc.) and how long the document should be and whether it will include any tutorials. Thanks

**Comment by pratik2315** [comment]
Here's some of the sections I think it should contain. Can you please review it and add/remove anything wrong. Thanks, as for the timeline, I think it should be done within the first week of august. 

• Setting up the repo - Fork, Clone and adding upstream connection to the repo
• Work specific to ifc-three - These section will contain steps specific to ifc-three. For eg. Any npm libraries a developer needs to work on ifcthree, recommended IDE, starter code etc. 
• Best practices - Working on a separate branch, rebase, merge conflicts, what to do when faced with an error etc. 
• When creating a new issue (practices to follow when creating a new issues, tagging a maintainer, discussions) 
• Code of conduct
• Community section
• Communication channel hyperlinks  and rules of the chat servers

**Comment by agviegas** [comment]
Hey @pratik2315 sorry for the delay in the response! All those points should great. In addition to what you mention, I would also include the use of yarn to build the repo, and not npm. Let me know if you have any questions regarding any of this! 👌

**Comment by pratik2315** [comment]
Thanks! I'll add that instead of npm👍
I am still confused about in what repository should I include the contribution document? Is it:

• Ifcjs/info or
• ifcjs/helloworld

**Comment by pratik2315** [comment]
As for the deadline, can I get this done by 15th august? I know it may seem too much time for a contribution page but im still getting familiar with how the IFC community functions. And I want to perfect the contribution section and hence dont want to rush it😅

**Comment by agviegas** [comment]
@pratik2315 Sorry, the text for the tutorials is generic. The guide can be just a page of this repository, don't worry about the examples (helloworld)! 

Also, we have just automated the bounty system :) Create a comment just containing the text `::take` and you will be good to go. You can see an example of that [here](https://github.com/ifcjs/info/issues/47#issuecomment-1205890048). Let me know if you have any other questions!

**Comment by pratik2315** [comment]
Understood! Thanks a lot for all the explanations. Will submit a PR on it tomorrow to show all the progress.

**Comment by pratik2315** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @pratik2315! Thanks for taking this bounty! The due date is August 26, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment]
### 🔴🔴🔴

Hi, @pratik2315! The date is past due, your assignment has been revoked. It’s now available for anyone to take.

**Comment by pkpndy** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @pkpndy! Thanks for taking this bounty! The due date is September 18, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by pkpndy** [comment]
::extend

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::extend

Hi, @pkpndy! The due date is successfully extended by 21 days to October 9, 2022 UTC.

**Comment by pkpndy** [comment]
Hi @agviegas I have submitted a Pull Request. 
Please review it and merge it or suggest necessary changes. 
Thankyou

**Comment by agviegas** [comment]
Merged! Next time, try to name the PR with the same name as this issue. You can now finish this with the `::done` command.

**Comment by pkpndy** [comment]
> Merged! Next time, try to name the PR with the same name as this issue. You can now finish this with the `::done` command.

Will do it from next time, thanks.

**Comment by pkpndy** [comment]
::done

**Comment by pkpndy** [comment]
::done

**Comment by pkpndy** [comment]
@agviegas I think `::done` is not working for me, is it because I didn't use PR name same as issue?

**Comment by agviegas** [comment]
::done

**Comment by agviegas** [comment]
@pkpndy simply create the expense in opencollective and we'll approve it!

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::done

Hi, @pkpndy! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).

**Comment by pkpndy** [comment]
::expense::97877

**Comment by agviegas** [comment]
### 🔴🔴🔴

> ::expense::97877

Hi, @pkpndy! We cannot find a new expense with that invoice number. Please re-check the invoice number and re-send the command using the correct one.
