### ISSUE TITLE
Automate Airtable

### ISSUE THREAD

**Issue by agviegas** [IFCjs/info#48]
📋 GENERAL: 

- Bounties page: https://bounties.ifcjs.io/
- Required skills: `C++`.
- Bounty: $200.

Right now we are using Airtable to manage the database of people who use the library, who do the courses, etc. We want to automate this to do things like, for example, when someone assigns themselves the github issue, airtable updates automatically. 

For more information, please contact us.

**Comment by izznatsir** [comment]
May I take this as well? I will start working on it next week.

**Comment by izznatsir** [comment]
I do have. I'm izznatsir also on Discord.

**Comment by jmcouffin** [comment]
That coulb be in you backyard @izznatsir 
I mentioned it to @agviegas in PM in discord already

Looking quickly at the bounty page on airtable page, the  Title of the bounty is not showing anymore, only the github # for the issue.
I could fix that if you give me access. But I guess this is a very quick fix

![image](https://user-images.githubusercontent.com/7872003/175504912-5486351b-0f74-4b62-a650-b33dcdf35983.png)

**Comment by izznatsir** [comment]
Oh sorry about that, I will fix that now

**Comment by jmcouffin** [comment]
Yes, it is fine on my side too.
Good Job @izznatsir

**Comment by izznatsir** [comment]
::expense::88334

**Comment by izznatsir** [comment]
::expense::88334

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::expense::88334

Hi, @izznatsir! Thanks for the confirmation! We’ll proceed to review the expense. Once it’s approved, the payment will be scheduled.

**Comment by agviegas** [comment]
### 🟢🟢🟢

Hi, @izznatsir! Your expense has been approved!

**Comment by agviegas** [comment]
### 🎉🎉🎉

Hi, @izznatsir! Thanks for your contributions! The reward of this bounty has been transferred to your Open Collective account.
