### ISSUE TITLE
IFC.js contact page

### ISSUE THREAD

**Issue by agviegas** [IFCjs/info#50]
## 📋 GENERAL: 

- Required skills: `Nothing!`.
- Bounty: $100.

________________________________________________________________________

## ⚔ CHALLENGE:

We want to create a page to tell the world how to contact us. We need a page similar to the crash course.

- https://courses.ifcjs.io/crash-course

If you have never done a webpage before, don't worry because this is super easy and you don't need to code for this. This page is made in the mailerlite web editor, which is a drag and drop web page builder that you can learn in 10 minutes and for which you don't need to know how to program.

________________________________________________________________________

## 👩‍⚖️ REQUIREMENTS: 

- Similar look to the original crash course page.

- Using different clip art images. 

________________________________________________________________________

## 🔥 STARTING MATERIAL: 

- Internal video tutorial where we explain the whole process step by step.

- Internal document with the specifications of the page.

- Access to our account and the mailerlite online editor to create the page.

- Our graphics archive, from which you can extract the clip art images you want.

You can use Photopea, a free image editor that we use to edit the graphics a bit. 

- https://www.photopea.com/

**Comment by rfdiazpr** [comment]
@agviegas i would also like to do this one

**Comment by agviegas** [comment]
All yours @rfdiazpr!

**Comment by pratik2315** [comment]
Hey there! I saw that this no work was done on this issue😅 If @agviegas is busy, I would love to start working on this issue!

**Comment by pratik2315** [comment]
> Hey there! I am a technical writer currently working under GSoD. I saw that this no work was done on this issue😅 If @agviegas is busy, I would love to start working on this issue!

**Comment by agviegas** [comment]
Hy @pratik2315 this is already assigned to @rfdiazpr. Nevertheless, stay tuned, as we will surely publish other similar bounties. Cheers!
