### ISSUE TITLE
B#68: Test automatic fake bounty

### ISSUE THREAD

**Issue by agviegas** [IFCjs/info#64]
## ☀ Info

- Bounty: $100
- Area: Docs
- Required skills: IFC.js
- Manager: @agviegas
- Bounties page: https://bounties.ifcjs.io

## 📜 Notes

⚔ CHALLENGE:

This is a test automatic bounty, please ignore this. We already have some tutorials in the documentation, so this is just a matter of creating a new one. For example:

- https://ifcjs.github.io/info/docs/Hello%20world

The tutorial should be made in the repository IFCjs/info. We use docusaurus for documentation. No worries, you don't need to know docusaurus to do this: just copy and paste what we do in other tutorials and you should be ready to go.

- https://github.com/ifcjs/info

The example developed in the tutorial should be made in the repository IFCjs/hello-world.

- https://github.com/ifcjs/hello-world

________________________________________________________________________

👩‍⚖️ REQUIREMENTS: 

- Similar look to other tutorials.

________________________________________________________________________

🔥 STARTING MATERIAL: 

Take a look at how other tutorials are made, and ask us anything you need!

**Comment by agviegas** [comment]
## 🤖 Bounty Bot

To interact with the bounty bot to manipulate this bounty, send a comment that only contains one of these commands:

### ::take

Assign yourself to the bounty. The due date of your assignment is the next 21st date UTC.

Requirements:
- Sender: Anyone
- Status: Available

### ::extend

Extend the due date by 21 days. Can only be done once.

Requirements:
- Sender: Assignee
- Status: In progress

### ::freeze

Freeze the bounty clock. The due date will be adjusted once the `!::unfreeze` is executed. The bounty manager can use this while reviewing the works without decreasing the duration available for the assignee.

Requirements:
- Sender: Manager
- Status: In progress
- Frozen: False

### ::unfreeze

Unfreeze the bounty clock. The new due date will be informed.

Requirements:
- Sender: Manager
- Status: In progress
- Frozen: True

### ::done

Change the status of this bounty to done. If your tasks require you to create pull requests, a PR title that either starts with the bounty ID or is exactly the same as the bounty name will automatically do the same thing when merged.

Requirements:
- Sender: Manager
- Status: In progress

### !::undone

Change the status of this bounty to in progress. Use this if the bounty is marked as done by mistake.

Requirements:
- Sender: Manager
- Status: Done

### ::drop
Give up on this bounty.

Requirements:
- Sender: Assignee
- Status: In progress

### ::expense::_____

After you’re done with the tasks, you need to submit an expense to IFC.js Open Collective. To ensure the authenticity of the expense, you need to tell us the invoice number via this command. Replace the `_____` with the invoice number (only the number).

Requirements:
- Sender: Assignee
- Status: Done

**Comment by izznatsir** [comment]
::take

**Comment by izznatsir** [comment]
::take

**Comment by izznatsir** [comment]
::take

**Comment by izznatsir** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @agviegas! Thanks for taking this bounty! The due date is August 18, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @izznatsir! Thanks for taking this bounty! The due date is August 18, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by izznatsir** [comment]
::drop

**Comment by izznatsir** [comment]
::drop

**Comment by izznatsir** [comment]
::drop

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::drop

Hi, @izznatsir! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by izznatsir** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @izznatsir! Thanks for taking this bounty! The due date is August 18, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by izznatsir** [comment]
::drop

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::drop

Hi, @izznatsir! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by izznatsir** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @izznatsir! Thanks for taking this bounty! The due date is August 18, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by izznatsir** [comment]
::extend

**Comment by agviegas** [comment]
### 🔴🔴🔴

> ::extend

Hi, @izznatsir! The due date can only be extended once.

**Comment by izznatsir** [comment]
::extend

**Comment by agviegas** [comment]
### 🔴🔴🔴

> ::extend

Hi, @izznatsir! The due date can only be extended once.

**Comment by izznatsir** [comment]
::extend

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::extend

Hi, @izznatsir! The due date is successfully extended by 21 days to September 8, 2022 UTC.

**Comment by izznatsir** [comment]
::freeze

**Comment by agviegas** [comment]
::freeze

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::freeze

Hi, @izznatsir! The clock has been frozen. The due date will be adjusted once the `::unfreeze` command is executed.

**Comment by agviegas** [comment]
::unfreeze

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::unfreeze

Hi, @izznatsir!  The due date has been adjusted to September 8, 2022 UTC. The clock is now ticking!

**Comment by agviegas** [comment]
::done

**Comment by izznatsir** [comment]
::done

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::done

Hi, @izznatsir! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).

**Comment by agviegas** [comment]
::undone

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::undone

Hi, @izznatsir! The bounty's status has been reverted back to in progress. The due date is August 4, 2022 UTC.

**Comment by agviegas** [comment]
::done

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::done

Hi, @izznatsir! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).

**Comment by agviegas** [comment]
::undone

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::undone

Hi, @izznatsir! The bounty's status has been reverted back to in progress. The due date is August 4, 2022 UTC.

**Comment by agviegas** [comment]
::done

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::done

Hi, @izznatsir! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).

**Comment by agviegas** [comment]
::undone

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::undone

Hi, @izznatsir! The bounty's status has been reverted back to in progress. The due date is August 4, 2022 UTC.

**Comment by agviegas** [comment]
::done

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::done

Hi, @izznatsir! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).

**Comment by izznatsir** [comment]
::expense::00000

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::expense::00000

Hi, @izznatsir! Thanks for the confirmation! We’ll proceed to review the expense. Once it’s approved, the payment will be scheduled.

**Comment by izznatsir** [comment]
::expense::10000

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::expense::10000

Hi, @izznatsir! Thanks for the confirmation! We’ll proceed to review the expense. Once it’s approved, the payment will be scheduled.

**Comment by izznatsir** [comment]
::expense::10000

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::expense::10000

Hi, @izznatsir! Thanks for the confirmation! We’ll proceed to review the expense. Once it’s approved, the payment will be scheduled.

**Comment by izznatsir** [comment]
::expense::10000

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::expense::10000

Hi, @izznatsir! Thanks for the confirmation! We’ll proceed to review the expense. Once it’s approved, the payment will be scheduled.

**Comment by izznatsir** [comment]
::expense::10000

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::expense::10000

Hi, @izznatsir! Thanks for the confirmation! We’ll proceed to review the expense. Once it’s approved, the payment will be scheduled.

**Comment by izznatsir** [comment]
::expense::10000

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::expense::10000

Hi, @izznatsir! Thanks for the confirmation! We’ll proceed to review the expense. Once it’s approved, the payment will be scheduled.

**Comment by izznatsir** [comment]
::expense::10000

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::expense::10000

Hi, @izznatsir! Thanks for the confirmation! We’ll proceed to review the expense. Once it’s approved, the payment will be scheduled.

**Comment by izznatsir** [comment]
::expense::10000

**Comment by izznatsir** [comment]
::expense::10000

**Comment by agviegas** [comment]
### 🔴🔴🔴

> ::expense::10000

Hi, @izznatsir! We cannot find the expense with that invoice number. Please re-check the invoice number and re-send the command using the correct one.

**Comment by izznatsir** [comment]
::expense::3453443

**Comment by agviegas** [comment]
### 🔴🔴🔴

> ::expense::3453443

Hi, @izznatsir! We cannot find the expense with that invoice number. Please re-check the invoice number and re-send the command using the correct one.

**Comment by izznatsir** [comment]
::expense::82762

**Comment by agviegas** [comment]
### 🔴🔴🔴

> ::expense::82762

Hi, @izznatsir! We cannot find a new expense with that invoice number. Please re-check the invoice number and re-send the command using the correct one.

**Comment by agviegas** [comment]
!::undone

**Comment by agviegas** [comment]
::undone

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::undone

Hi, @izznatsir! The bounty's status has been reverted back to in progress. The due date is August 7, 2022 UTC.

**Comment by agviegas** [comment]
::freeze

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::freeze

Hi, @izznatsir! The clock has been frozen. The due date will be adjusted once the `::unfreeze` command is executed.

**Comment by agviegas** [comment]
::unfreeze

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::unfreeze

Hi, @izznatsir!  The due date has been adjusted to August 8, 2022 UTC. The clock is now ticking!

**Comment by agviegas** [comment]
### 🔴🔴🔴

Hi, @izznatsir! The date is past due, your assignment has been revoked. It’s now available for anyone to take.
