### ISSUE TITLE
B#69: Create tutorial for handling bounties

### ISSUE THREAD

**Issue by agviegas** [IFCjs/info#65]
## ☀ Info

- Bounty: $100
- Area: Docs
- Required skills: Nothing!
- Manager: @agviegas
- Bounties page: https://bounties.ifcjs.io

## 📜 Notes

⚔ CHALLENGE:

We need more tutorials to show to the world how to use IFC.js and what can they do with it. We already have some tutorials in the documentation, so this is just a matter of creating a new one. For example:

- https://ifcjs.github.io/info/docs/Hello%20world

The tutorial should be made in the repository IFCjs/info. We use docusaurus for documentation. No worries, you don't need to know docusaurus to do this: just copy and paste what we do in other tutorials and you should be ready to go.

- https://github.com/ifcjs/info

The example developed in the tutorial should be made in the repository IFCjs/hello-world.

- https://github.com/ifcjs/hello-world

________________________________________________________________________

👩‍⚖️ REQUIREMENTS: 

- Similar look to other tutorials.

________________________________________________________________________

🔥 STARTING MATERIAL: 

Take a look at how other tutorials are made, and ask us anything you need!

**Comment by agviegas** [comment]
## 🤖 Bounty Bot

To interact with the bounty bot to manipulate this bounty, send a comment that only contains one of these commands:

### ::take

Assign yourself to the bounty. The due date of your assignment is the next 21st date UTC.

Requirements:
- Sender: Anyone
- Status: Available

### ::extend

Extend the due date by 21 days. Can only be done once.

Requirements:
- Sender: Assignee
- Status: In progress

### ::freeze

Freeze the bounty clock. The due date will be adjusted once the `!::unfreeze` is executed. The bounty manager can use this while reviewing the works without decreasing the duration available for the assignee.

Requirements:
- Sender: Manager
- Status: In progress
- Frozen: False

### ::unfreeze

Unfreeze the bounty clock. The new due date will be informed.

Requirements:
- Sender: Manager
- Status: In progress
- Frozen: True

### ::done

Change the status of this bounty to done. If your tasks require you to create pull requests, a PR title that either starts with the bounty ID or is exactly the same as the bounty name will automatically do the same thing when merged.

Requirements:
- Sender: Manager
- Status: In progress

### ::undone

Change the status of this bounty to in progress. Use this if the bounty is marked as done by mistake.

Requirements:
- Sender: Manager
- Status: Done

### ::drop
Give up on this bounty.

Requirements:
- Sender: Assignee
- Status: In progress

### ::expense::_____

After you’re done with the tasks, you need to submit an expense to IFC.js Open Collective. To ensure the authenticity of the expense, you need to tell us the invoice number via this command. Replace the `_____` with the invoice number (only the number).

Requirements:
- Sender: Assignee
- Status: Done

**Comment by Jsanchez4** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @Jsanchez4! Thanks for taking this bounty! The due date is August 22, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment]
🟢🟢🟢

Hi, @Jsanchez4! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::expense::88676

Hi, @Jsanchez4! Thanks for the confirmation! We’ll proceed to review the expense. Once it’s approved, the payment will be scheduled.

**Comment by agviegas** [comment]
### 🟢🟢🟢

Hi, @Jsanchez4! Your [expense](https://opencollective.com/ifcjs/expenses/88676) has been approved!

**Comment by agviegas** [comment]
### 🎉🎉🎉

Hi, @Jsanchez4! Thanks for your contributions! The reward of this bounty has been transferred to your Open Collective account.
