### ISSUE TITLE
[Tuto idea] Getting all properties of one element

### ISSUE THREAD

**Issue by favreau84** [IFCjs/info#8]
## Context

From a BIM viewer, by selecting one element in a 3D view, we typically get access to all its properties : 

- the element "native" properties.
- the element type properties.
- specific properties defined in properties sets.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/18169247/127018380-3e3b3aaf-5cb1-44c4-bc0d-fdb2755d6d6e.png">

## Tuto idea

It would be great to have a tutorial that would explain how to traverse the IFC tree to get all the properties related to one element. 

The input would be one element selection (from the "picking" tutorial).

The output would be an object or array with all the properties that will simply be logged in the console.

## Typical use cases

The typical use case is to extract a table of properties related to one type of element.
The next step is usually to modify some values from Excel. 
So eventually, what would be fantastic would be to describe the steps to update the ifc file with the updated values :-)

**Comment by agviegas** [comment]
[There](https://ifcjs.github.io/info/docs/Guide/web-ifc-three/Tutorials/Properties) you go.
