### ISSUE TITLE
B#74: Marketing content creation (1 month)

### ISSUE THREAD

**Issue by agviegas** [IFCjs/info#80]
## ☀ Info

- Bounty: $500
- Area: Management
- Required skills: Three.js, JavaScript, IFC.js
- Manager: @agviegas
- Bounties page: https://bounties.ifcjs.io

## 📜 Notes

⚔ CHALLENGE:

We have developed a content creation strategy and are looking for someone to collaborate with copywriting. We have two channels to spread the content. Our social networks (Linkedin and Twitter) and our weekly newsletter.

Each week we propose a series of topics to publish daily on Linkedin and twitter and you will be in charge of writing following the guidelines we give you and scheduling the publications. 

In addition, once a week we publish our newsletter and we expect you to take care of the copywriting.

The bounty is monthly, but if you are good at it and you want to, you will always have priority to make the following bounties, related to content creation.

________________________________________________________________________

👩‍⚖️ REQUIREMENTS: 

- High level of written English. 
- Knowledge of the project. Valuable if you have done the IFC.js crash-course or if you are developing an application that demonstrates knowledge of the libraries.
- Coding skills. Some of topics are about coding, so we need you to know how to code to prepare the content to publish.
________________________________________________________________________

🔥 STARTING MATERIAL: 

We will give you access to an Airtable Base with information about previous posts on social media. You will have a list of the topics to be discussed each day, so you will not have to think about what to write about. Just based on the proposed topics you will have to develop the posts following the style of the previous ones.

As for the newsletter, we will prepare the topics together.

**Comment by agviegas** [comment]
## 🤖 Bounty Bot

To interact with the bounty bot to manipulate this bounty, send a comment that only contains one of these commands:

### ::take

Assign yourself to the bounty. The due date of your assignment is the next 21st date UTC.

Requirements:
- Sender: Anyone
- Status: Available

### ::extend

Extend the due date by 21 days. Can only be done once.

Requirements:
- Sender: Assignee
- Status: In progress

### ::freeze

Freeze the bounty clock. The due date will be adjusted once the `!::unfreeze` is executed. The bounty manager can use this while reviewing the works without decreasing the duration available for the assignee.

Requirements:
- Sender: Manager
- Status: In progress
- Frozen: False

### ::unfreeze

Unfreeze the bounty clock. The new due date will be informed.

Requirements:
- Sender: Manager
- Status: In progress
- Frozen: True

### ::done

Change the status of this bounty to done. If your tasks require you to create pull requests, a PR title that either starts with the bounty ID or is exactly the same as the bounty name will automatically do the same thing when merged.

Requirements:
- Sender: Manager
- Status: In progress

### ::undone

Change the status of this bounty to in progress. Use this if the bounty is marked as done by mistake.

Requirements:
- Sender: Manager
- Status: Done

### ::drop
Give up on this bounty.

Requirements:
- Sender: Assignee
- Status: In progress

### ::expense::_____

After you’re done with the tasks, you need to submit an expense to IFC.js Open Collective. To ensure the authenticity of the expense, you need to tell us the invoice number via this command. Replace the `_____` with the invoice number (only the number).

Requirements:
- Sender: Assignee
- Status: Done

**Comment by Pragya08Kankaria** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @Pragya08Kankaria! Thanks for taking this bounty! The due date is September 13, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by Pragya08Kankaria** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @Pragya08Kankaria! Thanks for taking this bounty! The due date is October 5, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!
